server:
  port: 8092

spring:
  # DB?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root
  thymeleaf:
    cache: false
  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:
    open-in-view: false